import type { RoadmapPhase } from '../types';

export const phases: RoadmapPhase[] = [
    {
        id: 'phase-1',
        number: 1,
        title: 'Nền tảng',
        subtitle: 'Xây dựng vốn từ và phát âm cơ bản',
        duration: 'Tuần 1–2',
        icon: '🌱',
        color: 'bg-emerald-50 dark:bg-emerald-900/20',
        borderColor: 'border-emerald-200 dark:border-emerald-700/50',
        badgeColor: 'bg-emerald-500',
        lineColor: 'bg-emerald-400',
        tasks: [
            { id: 't1-1', label: 'Từ vựng giao tiếp hàng ngày', desc: '20 từ thiết yếu nhất khi gặp người lạ, chào hỏi, giới thiệu bản thân', section: 'vocabulary', xpReward: 50, tag: 'Từ vựng' },
            { id: 't1-2', label: 'Phát âm 5 nguyên âm cơ bản', desc: 'Âm /æ/, /ɑː/, /ɔː/, /uː/, /ɜː/ — nền tảng để đọc bất kỳ từ nào', section: 'speaking', xpReward: 40, tag: 'Phát âm' },
            { id: 't1-3', label: 'Mẫu câu chào hỏi & giới thiệu', desc: '"Hello, I\'m..." / "Nice to meet you" / "How are you doing?"', section: 'grammar', xpReward: 45, tag: 'Ngữ pháp' },
            { id: 't1-4', label: 'Luyện nói 3 câu cơ bản với AI', desc: 'Thực hành ngay với AI để kiểm tra phát âm và sửa lỗi sớm', section: 'speaking', xpReward: 60, tag: 'Nói' },
            { id: 't1-5', label: 'Tạo bộ Flashcards tuần 1', desc: 'Lưu các từ mới học được vào flashcard để ôn tập mỗi ngày', section: 'flashcards', xpReward: 30, tag: 'Flashcards' },
        ],
    },
    {
        id: 'phase-2',
        number: 2,
        title: 'Xây dựng câu',
        subtitle: 'Ghép từ thành câu hoàn chỉnh trong thực tế',
        duration: 'Tuần 3–4',
        icon: '🌿',
        color: 'bg-blue-50 dark:bg-blue-900/20',
        borderColor: 'border-blue-200 dark:border-blue-700/50',
        badgeColor: 'bg-blue-500',
        lineColor: 'bg-blue-400',
        unlockAfter: 3,
        tasks: [
            { id: 't2-1', label: 'Hiện tại đơn & Hiện tại tiếp diễn', desc: 'Hai thì quan trọng nhất — dùng mỗi ngày để nói về thói quen và hiện tại', section: 'grammar', xpReward: 55, tag: 'Ngữ pháp' },
            { id: 't2-2', label: 'Từ vựng chủ đề Công việc', desc: 'Từ dùng trong văn phòng, email, họp hành — thực dụng ngay', section: 'vocabulary', xpReward: 50, tag: 'Từ vựng' },
            { id: 't2-3', label: 'Hội thoại mua sắm', desc: 'Tình huống thực tế: hỏi giá, chọn size, trả tiền — dễ bắt đầu', section: 'conversation', xpReward: 65, tag: 'Hội thoại' },
            { id: 't2-4', label: 'Luyện nói câu trung cấp với AI', desc: '"Could you please..." / "I would like to..." — lịch sự và tự nhiên hơn', section: 'speaking', xpReward: 70, tag: 'Nói' },
            { id: 't2-5', label: 'Flashcards từ bài báo tiếng Anh', desc: 'Dán đoạn tin tức đơn giản — AI trích từ mới và tạo thẻ tự động', section: 'flashcards', xpReward: 40, tag: 'Flashcards' },
        ],
    },
    {
        id: 'phase-3',
        number: 3,
        title: 'Hội thoại thực chiến',
        subtitle: 'Đối thoại liên tục và xử lý tình huống bất ngờ',
        duration: 'Tuần 5–8',
        icon: '🌳',
        color: 'bg-purple-50 dark:bg-purple-900/20',
        borderColor: 'border-purple-200 dark:border-purple-700/50',
        badgeColor: 'bg-purple-500',
        lineColor: 'bg-purple-400',
        unlockAfter: 4,
        tasks: [
            { id: 't3-1', label: 'Hội thoại nhà hàng & sân bay', desc: 'Tình huống du lịch thực tế: đặt bàn, check-in, hỏi thông tin chuyến bay', section: 'conversation', xpReward: 75, tag: 'Hội thoại' },
            { id: 't3-2', label: 'Thì quá khứ & Hiện tại hoàn thành', desc: 'Kể chuyện, chia sẻ kinh nghiệm — mở rộng khả năng diễn đạt', section: 'grammar', xpReward: 60, tag: 'Ngữ pháp' },
            { id: 't3-3', label: 'Hội thoại họp công việc', desc: 'Trình bày ý kiến, đặt câu hỏi, phản hồi chuyên nghiệp trong môi trường công sở', section: 'conversation', xpReward: 85, tag: 'Hội thoại' },
            { id: 't3-4', label: 'Nâng cấp phát âm: âm nối', desc: 'Linking sounds — bí kíp nghe tự nhiên như người bản ngữ thật sự', section: 'speaking', xpReward: 80, tag: 'Nói' },
            { id: 't3-5', label: 'Từ vựng IT & Công nghệ', desc: '20 thuật ngữ kỹ thuật thiết yếu: algorithm, deployment, repository...', section: 'vocabulary', xpReward: 55, tag: 'Từ vựng' },
        ],
    },
    {
        id: 'phase-4',
        number: 4,
        title: 'Lưu loát',
        subtitle: 'Phản xạ tức thì, không cần chuẩn bị',
        duration: 'Tuần 9+ · Liên tục',
        icon: '🏆',
        color: 'bg-amber-50 dark:bg-amber-900/20',
        borderColor: 'border-amber-200 dark:border-amber-700/50',
        badgeColor: 'bg-gradient-to-r from-amber-400 to-orange-500',
        lineColor: 'bg-amber-400',
        unlockAfter: 4,
        tasks: [
            { id: 't4-1', label: 'Hội thoại tự do không chuẩn bị', desc: 'Nói về bất kỳ chủ đề nào AI đưa ra — không có kịch bản, phản xạ tự nhiên', section: 'conversation', xpReward: 100, tag: 'Tự do' },
            { id: 't4-2', label: 'Thì tương lai & điều kiện', desc: '"If I were you..." / "I will have finished by..." — diễn đạt phức tạp', section: 'grammar', xpReward: 70, tag: 'Ngữ pháp' },
            { id: 't4-3', label: 'Phân tích lỗi sai cá nhân', desc: 'Xem lại sổ tay từ vựng — ôn đúng những từ bạn hay quên nhất', section: 'vocab-notebook', xpReward: 60, tag: 'Ôn tập' },
            { id: 't4-4', label: 'Nói nâng cao: thuyết phục & tranh luận', desc: '"On the other hand..." / "I strongly believe that..." — cấp độ học thuật', section: 'speaking', xpReward: 120, tag: 'Nói' },
            { id: 't4-5', label: 'Duy trì streak 30 ngày', desc: 'Học đều đặn mỗi ngày — thói quen là chìa khóa duy nhất để thành thạo', xpReward: 200, tag: '🔥 Thử thách' },
        ],
    },
];

export const tagColors: Record<string, string> = {
    'Từ vựng': 'bg-blue-100 text-blue-700 dark:bg-blue-900/40 dark:text-blue-300',
    'Phát âm': 'bg-purple-100 text-purple-700 dark:bg-purple-900/40 dark:text-purple-300',
    'Ngữ pháp': 'bg-emerald-100 text-emerald-700 dark:bg-emerald-900/40 dark:text-emerald-300',
    'Nói': 'bg-red-100 text-red-700 dark:bg-red-900/40 dark:text-red-300',
    'Flashcards': 'bg-amber-100 text-amber-700 dark:bg-amber-900/40 dark:text-amber-300',
    'Hội thoại': 'bg-indigo-100 text-indigo-700 dark:bg-indigo-900/40 dark:text-indigo-300',
    'Ôn tập': 'bg-pink-100 text-pink-700 dark:bg-pink-900/40 dark:text-pink-300',
    'Tự do': 'bg-orange-100 text-orange-700 dark:bg-orange-900/40 dark:text-orange-300',
    '🔥 Thử thách': 'bg-red-100 text-red-700 dark:bg-red-900/40 dark:text-red-300',
};
